package com.hotsun.mqxxgl.busi.model;
// default package
// Generated 2017-3-30 16:56:24 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * FwLdxx generated by hbm2java
 */
public class FwLdxx  implements Serializable{

	private String ldid;
	private String cunid;
	private String zuid;
	private String ldmc;
	private String ldaddr;
	private String cellnum;
	private String floornum;
	private String zxlxdm;
	private String zxrq;
	private String bz;
	private String qrztdm;

	public String getLdid() {
		return ldid;
	}

	public void setLdid(String ldid) {
		this.ldid = ldid;
	}

	public String getCunid() {
		return cunid;
	}

	public void setCunid(String cunid) {
		this.cunid = cunid;
	}

	public String getZuid() {
		return zuid;
	}

	public void setZuid(String zuid) {
		this.zuid = zuid;
	}

	public String getLdmc() {
		return ldmc;
	}

	public void setLdmc(String ldmc) {
		this.ldmc = ldmc;
	}

	public String getLdaddr() {
		return ldaddr;
	}

	public void setLdaddr(String ldaddr) {
		this.ldaddr = ldaddr;
	}

	public String getCellnum() {
		return cellnum;
	}

	public void setCellnum(String cellnum) {
		this.cellnum = cellnum;
	}

	public String getFloornum() {
		return floornum;
	}

	public void setFloornum(String floornum) {
		this.floornum = floornum;
	}

	public String getZxlxdm() {
		return zxlxdm;
	}

	public void setZxlxdm(String zxlxdm) {
		this.zxlxdm = zxlxdm;
	}

	public String getZxrq() {
		return zxrq;
	}

	public void setZxrq(String zxrq) {
		this.zxrq = zxrq;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getQrztdm() {
		return qrztdm;
	}

	public void setQrztdm(String qrztdm) {
		this.qrztdm = qrztdm;
	}

	public String getQrsj() {
		return qrsj;
	}

	public void setQrsj(String qrsj) {
		this.qrsj = qrsj;
	}

	public String getQrrxm() {
		return qrrxm;
	}

	public void setQrrxm(String qrrxm) {
		this.qrrxm = qrrxm;
	}

	public String getAdddatetime() {
		return adddatetime;
	}

	public void setAdddatetime(String adddatetime) {
		this.adddatetime = adddatetime;
	}

	public String getAdduser() {
		return adduser;
	}

	public void setAdduser(String adduser) {
		this.adduser = adduser;
	}

	public String getChgdatetime() {
		return chgdatetime;
	}

	public void setChgdatetime(String chgdatetime) {
		this.chgdatetime = chgdatetime;
	}

	public String getChguser() {
		return chguser;
	}

	public void setChguser(String chguser) {
		this.chguser = chguser;
	}

	public String getLastupddt() {
		return lastupddt;
	}

	public void setLastupddt(String lastupddt) {
		this.lastupddt = lastupddt;
	}

	public String getXjrq() {
		return xjrq;
	}

	public void setXjrq(String xjrq) {
		this.xjrq = xjrq;
	}

	public String getFwjgdm() {
		return fwjgdm;
	}

	public void setFwjgdm(String fwjgdm) {
		this.fwjgdm = fwjgdm;
	}

	private String qrsj;
	private String qrrxm;
	private String adddatetime;
	private String adduser;
	private String chgdatetime;
	private String chguser;
	private String lastupddt;
	
	private String xjrq;
	private String fwjgdm;




}
