package com.hotsun.mqxxgl.busi.model;
// default package
// Generated 2017-3-30 16:56:24 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * FwLdxx generated by hbm2java
 */
public class FwLdxx  implements Serializable{

	private long ldid;
	private long cunid;
	private long zuid;
	private String ldmc;
	private String ldaddr;
	private short cellnum;
	private short floornum;
	private String zxlxdm;
	private Date zxrq;
	private String bz;
	private String qrztdm;
	private Date qrsj;
	private String qrrxm;
	private Date adddatetime;
	private String adduser;
	private Date chgdatetime;
	private String chguser;
	private Date lastupddt;
	
	private Date xjrq;
	private String fwjgdm;

	public FwLdxx() {
	}
	public long getLdid() {
		return ldid;
	}

	public void setLdid(long ldid) {
		this.ldid = ldid;
	}

	public long getCunid() {
		return cunid;
	}

	public void setCunid(long cunid) {
		this.cunid = cunid;
	}

	public long getZuid() {
		return zuid;
	}

	public void setZuid(long zuid) {
		this.zuid = zuid;
	}

	public String getLdmc() {
		return ldmc;
	}

	public void setLdmc(String ldmc) {
		this.ldmc = ldmc;
	}

	public String getLdaddr() {
		return ldaddr;
	}

	public void setLdaddr(String ldaddr) {
		this.ldaddr = ldaddr;
	}

	public short getCellnum() {
		return cellnum;
	}

	public void setCellnum(short cellnum) {
		this.cellnum = cellnum;
	}

	public short getFloornum() {
		return floornum;
	}

	public void setFloornum(short floornum) {
		this.floornum = floornum;
	}

	public String getZxlxdm() {
		return zxlxdm;
	}

	public void setZxlxdm(String zxlxdm) {
		this.zxlxdm = zxlxdm;
	}

	public Date getZxrq() {
		return zxrq;
	}

	public void setZxrq(Date zxrq) {
		this.zxrq = zxrq;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getQrztdm() {
		return qrztdm;
	}

	public void setQrztdm(String qrztdm) {
		this.qrztdm = qrztdm;
	}

	public Date getQrsj() {
		return qrsj;
	}

	public void setQrsj(Date qrsj) {
		this.qrsj = qrsj;
	}

	public String getQrrxm() {
		return qrrxm;
	}

	public void setQrrxm(String qrrxm) {
		this.qrrxm = qrrxm;
	}

	public Date getAdddatetime() {
		return adddatetime;
	}

	public void setAdddatetime(Date adddatetime) {
		this.adddatetime = adddatetime;
	}

	public String getAdduser() {
		return adduser;
	}

	public void setAdduser(String adduser) {
		this.adduser = adduser;
	}

	public Date getChgdatetime() {
		return chgdatetime;
	}

	public void setChgdatetime(Date chgdatetime) {
		this.chgdatetime = chgdatetime;
	}

	public String getChguser() {
		return chguser;
	}

	public void setChguser(String chguser) {
		this.chguser = chguser;
	}

	public Date getLastupddt() {
		return lastupddt;
	}

	public void setLastupddt(Date lastupddt) {
		this.lastupddt = lastupddt;
	}

	public Date getXjrq() {
		return xjrq;
	}

	public void setXjrq(Date xjrq) {
		this.xjrq = xjrq;
	}

	public String getFwjgdm() {
		return fwjgdm;
	}

	public void setFwjgdm(String fwjgdm) {
		this.fwjgdm = fwjgdm;
	}


}
