package com.hotsun.mqxxgl.busi.model.sysbeans;
// default package
// Generated 2017-3-30 16:56:24 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.List;
import java.util.Map;

/**
 * FwLdxx generated by hbm2java
 */
public class AddResponseResults implements Serializable{

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}



	private String status;
	private String msg;

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}
}
